# Generated by Django 2.0.6 on 2019-07-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('phone', models.CharField(max_length=20, null=True, unique=True)),
                ('role_id', models.PositiveSmallIntegerField(default=1)),
                ('is_email_confirmed', models.BooleanField(default=False)),
                ('confirm_email_key', models.CharField(max_length=100, null=True)),
                ('reset_password_key', models.CharField(max_length=100, null=True)),
                ('reset_password_expired_at', models.DateTimeField(default=None, null=True)),
                ('avatar', models.CharField(default=None, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
